- name: install dependencies
  yum: name={{item}} enablerepo=epel state=installed
  with_items:
     - cmake
  tags: mysql

- name: MySQL Install
  yum: pkg=mysql-server state=installed
  register: installed
  tags: mysql

- name: MySQL changed permission
  file: path=/var/lib/mysql/ owner=mysql group=mysql state=directory recurse=yes
  tags: mysql

- name: deploy my.cnf
  template: src=my.cnf.j2 dest=/etc/my.cnf owner=mysql group=mysql mode=0755
  tags: mysql

- name: mysql_multi1 initialize data
  command: mysql_install_db --datadir=/var/lib/mysql/multi1 --user=mysql creates=/var/lib/mysql/multi1
  tags: mysql

- name: mysql_multi2 initialize data
  command: mysql_install_db --datadir=/var/lib/mysql/multi2 --user=mysql creates=/var/lib/mysql/multi2
  tags: mysql

- name: deploy mysql_multi init script
  template: src=mysqld_multi.j2 dest=/etc/init.d/mysqld_multi mode=755
  tags: mysql

- name: which mysqld_multi chkconfig added
  shell: chkconfig --list | grep 'mysqld_multi' | awk '{print $1}'
  when: installed|changed
  tags: mysql

- name: added service mysqld_multi
  shell: chkconfig --add mysqld_multi
  when: installed|changed
  tags: mysql

- name: chkconfig on mysqld_multi
  shell: chkconfig mysqld_multi on
  when: installed|changed
  tags: mysql

- name: start MySQL Multi mode
  shell: /etc/init.d/mysqld_multi start
  when: installed|changed
  tags: mysql

- name: mysqld_multi started deley wait
  pause: seconds=2
  when: installed|changed
  tags: mysql

- name: mysqlAdmin setting password mysql_multi1
  shell: mysqladmin -uroot -P3306 -h'{{ mysqlHost }}' password '{{ mysqlDefaultPassword  }}'
  when: installed|changed
  tags: mysql

- name: mysqlAdmin setting password mysql_multi2
  shell: mysqladmin -uroot -P3307 -h'{{ mysqlHost }}' password '{{ mysqlDefaultPassword  }}'
  when: installed|changed
  tags: mysql

- name: delete mysql root user with no passowrd mysql_multi1
  shell: mysql -uroot -P3306 -h'{{ mysqlHost }}'  -p'{{ mysqlDefaultPassword }}' -e "DELETE FROM mysql.user WHERE Password = '';"
  when: installed|changed
  tags: mysql

- name: delete mysql root user with no passowrd mysql_multi2
  shell: mysql -uroot -P3307 -h'{{ mysqlHost }}'  -p'{{ mysqlDefaultPassword }}' -e "DELETE FROM mysql.user WHERE Password = '';"
  when: installed|changed
  tags: mysql
