- name: Check for installed apps(packer)
  shell: brew cask list | grep -c packer
  register: app_installed
  changed_when: app_installed.stdout != "1"

- name: install cask packer
  shell: brew cask install packer
  changed_when: app_installed.stdout != "1"
