- name: Create the repository for Jenkins
  copy: src=jenkins.repo dest=/etc/yum.repos.d/jenkins.repo
  tags: jenkins

- name: Added Jenkins RPM Key
  rpm_key: state=present key=http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
  tags: jenkins

- name: Jenkins Install
  yum: pkg=jenkins state=installed
  tags: jenkins

- name: added iptables
  lineinfile: dest=/etc/sysconfig/iptables
              state=present
              regexp='^-A INPUT -m state --state NEW -m tcp -p tcp --dport {{ iptables.ports.jenkins }} -j ACCEPT'
              insertafter='^-A INPUT -m state'
              line='-A INPUT -m state --state NEW -m tcp -p tcp --dport {{ iptables.ports.jenkins }} -j ACCEPT'

- name: started jenkins
  service: name=jenkins state=started

- name: iptables restart
  service: name=iptables state=restarted
  when: result.changed

- name: jenkins started make plugin deley wait
  pause: seconds=3
