- name: Check for installed apps(XQuartz)
  shell: brew cask list | grep -c xquartz
  register: app_installed
  changed_when: app_installed.stdout != "1"

- name: install cask XQuartz
  shell: brew cask install xquartz
  changed_when: app_installed.stdout != "1"
