- name: search terget BoxName
  shell: cat {{ ansible_env.PWD }}/../Vagrantfile | grep 'BOX_NAME =' | awk '{print $3}' | sed -e 's/"//g'
  register: box_name
  changed_when: False

- name: search duplicate virtualbox BoxName
  shell: VBoxManage list vms | grep -c {{ box_name.stdout }}
  register: is_box
  changed_when: is_box.stdout != "1"

- name: delete duplicate virtualbox BoxName
  shell: VBoxManage unregistervm {{ box_name.stdout }}
  changed_when: is_box.stdout != "1"

- debug: msg="Next Step is Command to vagrant up --provsion"

