#!/usr/bin/env bash
#
set -e

pwd=$(pwd)
ip_address=$(cat ${pwd}/Vagrantfile | grep 'config.vm.network :private_network, ip: ' | awk '{print $4}' | sed -e "s/,//g" | sed -e 's/"//g')

scp -P 22 -i ~/.vagrant.d/insecure_private_key  ~/.vagrant.d/insecure_private_key vagrant@${ip_address}:/home/vagrant/.ssh/id_rsa
ssh -i ~/.vagrant.d/insecure_private_key vagrant@${ip_address} chmod 0600 /home/vagrant/.ssh/id_rsa
ssh -i ~/.vagrant.d/insecure_private_key vagrant@${ip_address} chown -R vagrant:vagrant /home/vagrant/.ssh/id_rsa
