- name: Create directory /usr/local/phpenv/plugins
  file: path=/usr/local/phpenv/plugins state=directory mode=775
  tags: install-php-build

- name: check php-build installed
  command: echo 'installed' creates=/usr/local/phpenv/plugins/php-build
  register: has_php_build
  tags: install-php-build

- name: install php-build
  git: repo=https://github.com/CHH/php-build.git
       dest=/usr/local/phpenv/plugins/php-build
  when: has_php_build|changed
  tags: install-php-build
