- name: Create directory /usr/local/phpenv/plugins
  file: path=/usr/local/phpenv/plugins state=directory mode=775
  tags: phpenv-apache-version

- name: check php-apache-version installed
  command: echo 'installed' creates=/usr/local/phpenv/plugins/phpenv-apache-version
  register: has_phpenv_apache_version
  tags: phpenv-apache-version

- name: install phpenv-apache-version
  git: repo=https://github.com/garamon/phpenv-apache-version.git
       dest=/usr/local/phpenv/plugins/phpenv-apache-version
  when: has_phpenv_apache_version|changed
  tags: phpenv-apache-version

- name: phpenv-apache version changed
  shell: source /etc/profile; phpenv apache-version {{ phpenvBuildVersion }} > /dev/null
  changed_when: result.stdout.find('{{ phpenvBuildVersion }}') != 0
  tags: phpenv-apache-version

- name: restart httpd
  service: name='httpd' state=restarted
  when: result.stdout.find('{{ phpenvBuildVersion }}') != 0
  tags: phpenv-apache-version

- name: change vhost.conf
  shell: cat /etc/httpd/conf.d/vhost.conf | awk /example.lo/'{print $2}'
  register: has_vhost_setting
  changed_when: has_vhost_setting.rc != 0
  tags: phpenv-apache-version
