- name: Create phpenv group
  group: name=phpenv state=present

- name: Check phpenv Exists
  shell: cat /etc/group | grep phpenv;
  register: result
  changed_when: result.stdout.find('phpenv') != 0

- name: User add phpenv group
  user: name={{ ansible_env.SUDO_USER }} groups=phpenv,wheel
  changed_when: result.stdout.find('phpenv') != 0

- name: install phpenv
  shell: curl https://raw.githubusercontent.com/CHH/phpenv/master/bin/phpenv-install.sh | bash
  register: installed
  args:
    creates: /usr/local/phpenv/bin/phpenv

- name: phpenv global dir mv
  shell: mv /root/.phpenv /usr/local/phpenv
  args:
    creates: /usr/local/phpenv/bin/phpenv

- name: set permissions
  file: path=/usr/local/phpenv mode=775 recurse=yes
  when: installed|changed

- name: phpenv Dir change group
  file: path=/usr/local/phpenv group=phpenv mode=0775 state=directory recurse=yes
  when: installed|changed

- name: phpenv shims change permission
  file: path=/usr/local/phpenv/shims state=directory mode=0777
  when: installed|changed

- name: deploy /etc/profiled.d/phpenv.sh
  template: src=phpenv.sh.j2 dest=/etc/profile.d/phpenv.sh mode=755

- name: deploy /usr/local/phpenv/versions/{{ phpenvBuildVersion }}/etc/conf.d/date.ini
  template: src=date.ini.j2 dest=/usr/local/phpenv/versions/{{ phpenvBuildVersion }}/etc/conf.d/date.ini mode=755
