- name: Check whether msgpack-php has already been installed
  stat: path=/usr/local/phpenv/versions/{{ phpenvBuildVersion }}/etc/conf.d/msgpack.ini
  register: msgpack_stat
  tags: extension-msgpack

- name: git clone msgpack-php
  git : repo=https://github.com/msgpack/msgpack-php.git
        dest=/tmp/msgpack-php
  tags: extension-msgpack

- name: install dependencies
  yum: name={{item}} enablerepo=epel state=installed
  with_items:
    - libtool

- name : make install msgpack-php
  shell: |
    cd /tmp/msgpack-php
    /usr/local/phpenv/shims/phpize
    ./configure --with-php-config=/usr/local/phpenv/shims/php-config
    make && make install
  tags: extension-msgpack
  when: msgpack_stat.stat.exists==false

- name : msgpack settings msgpack.ini
  template: src=msgpack.ini.j2 dest=/usr/local/phpenv/versions/{{ phpenvBuildVersion }}/etc/conf.d/msgpack.ini mode=0644
  tags: extension-msgpack
