- name: Check for installed apps(vagrant)
  shell: brew cask list | grep -c "^vagrant$"
  register: app_installed
  changed_when: app_installed.stdout != "1"

- name: install cask vagrant
  shell: brew cask install vagrant
  changed_when: app_installed.stdout != "1"
