- name: install dependencies
  yum: name={{item}} enablerepo=epel state=installed
  with_items:
    - autoconf
    - re2c
    - libmcrypt
    - libmcrypt-devel
    - libxml2-devel
    - bison
    - bison-devel
    - openssl-devel
    - curl-devel
    - libjpeg-devel
    - libpng-devel
    - libmcrypt-devel
    - readline-devel
    - libtidy-devel
    - libxslt-devel
    - httpd-devel
    - enchant-devel
    - libXpm
    - libXpm-devel
    - freetype-devel
    - t1lib
    - t1lib-devel
    - gmp-devel
    - libc-client-devel
    - libicu-devel
    - oniguruma-devel
    - net-snmp
    - net-snmp-devel
    - bzip2-devel
    - mysql-devel
    - gd-devel
    - firebird-devel
    - freetds-devel
    - unixODBC-devel
    - aspell-devel
    - libedit-devel
    - net-snmp-devel
    - recode-devel
    - openssl
    - openssl-devel
    - libtool-ltdl-devel
    - lemon

- name: deploy configure option
  template: src=default_configure_options.j2 dest=/usr/local/phpenv/plugins/php-build/share/php-build/default_configure_options
  tags: php-build-install-php

- name: deploy php definitions {{ phpenvBuildVersion }}
  template: src={{ phpenvBuildVersion }}.j2 dest=/usr/local/phpenv/plugins/php-build/share/php-build/definitions/{{ phpenvBuildVersion }}
  tags: php-build-install-php

- name: deploy php.conf to /etc/httpd/conf.d/php.conf
  template: src=php.conf.j2 dest=/etc/httpd/conf.d/php.conf
  register: deploy_php_conf
  tags: php-build-install-php

- name: Check phpenv Version Installed
  shell: source /etc/profile; phpenv versions | awk '/{{ phpenvBuildVersion }}/{print $2}'
  register: result
  changed_when: result.stdout.find('{{ phpenvBuildVersion }}') != 0
  tags: php-build-install-php

- name: Install PHP from phpenv
  shell: source /etc/profile; phpenv install {{ phpenvBuildVersion }}
  when: result.stdout.find('{{ phpenvBuildVersion }}') != 0
  tags: php-build-install-php

- name: Build phpenv change global
  shell: source /etc/profile; phpenv global {{ phpenvBuildVersion }}; phpenv rehash
  when: result.stdout.find('{{ phpenvBuildVersion }}') != 0
  tags: php-build-install-php

- name: changed libphp5.so permission
  file: path=/usr/lib64/httpd/modules/libphp5.so mode=775
  when: result.stdout.find('{{ phpenvBuildVersion }}') != 0
  tags: php-build-install-php

- name: Copy libphp5.so phpenv/versions
  shell: cp /usr/lib64/httpd/modules/libphp5.so /usr/local/phpenv/versions/{{ phpenvBuildVersion }}/libphp5.so
    creates=/usr/local/phpenv/versions/{{ phpenvBuildVersion }}/libphp5.so
  tags: php-build-install-php
